export const favoritesMockNFTS = [
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 1",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/thumbnail/TESTCOLLEC-7ada95-01",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 12",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://art-holst.com.ua/wp-content/uploads/s1200.jpg",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/thumbnail/TESTCOLLEC-7ada95-01",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 3",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://devnet-media.elrond.com/nfts/thumbnail/ONEOFONES-294b8b-01",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/thumbnail/TESTCOLLEC-7ada95-01",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 4",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://ipfs.io/ipfs/QmfELQ71ZdTQrZYTLepMwK6ZFAEJ3hLK4oFyWxtfJHzXdn",
    thumbnailUrl: "https://ipfs.io/ipfs/QmfELQ71ZdTQrZYTLepMwK6ZFAEJ3hLK4oFyWxtfJHzXdn",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 5",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://ipfs.io/ipfs/QmfELQ71ZdTQrZYTLepMwK6ZFAEJ3hLK4oFyWxtfJHzXdn",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/thumbnail/TESTCOLLEC-7ada95-01",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 6",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/thumbnail/TESTCOLLEC-7ada95-01",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 7",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
  {
    identifier: "TESTCOLLEC-7ada95-01",
    collection: "TESTCOLLEC-7ada95",
    attributes: "dGFnczp0ZXN0LG5mdDE7bWV0YWRhdGE6UW1ZYkZmdkNGeFRyOW1FN2cyVkMyQ05hdnU5bXNKZlpjYTVQbVdwWHBhR0sxZQ==",
    nonce: 1,
    type: "NonFungibleESDT",
    name: "FavoriteMOCK 8",
    creator: "erd17e4uuvhhnncye6mxxzffmgfhtyz8tpf4ug25he23z99j6yg8lwfqus4n28",
    royalties: 5,
    uris: ["aHR0cHM6Ly9pcGZzLmlvL2lwZnMvUW1aSGdBdlFiNHdLdzVENUVTYWRGWHY2SldxSHJ2R3dLUnVidFBaQ1VIRVgyaA=="],
    url: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    thumbnailUrl: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    tags: ["test", "nft1"],
    timestamp: new Date(),
    metadata: {
      description: 'string',
      fileType: 'string',
      fileUri: 'string',
      fileName: 'string',
    },
    owner: 'bereamu',
    fileType: "image/png",
    fileUri: "https://devnet-media.elrond.com/nfts/asset/QmZHgAvQb4wKw5D5ESadFXv6JWqHrvGwKRubtPZCUHEX2h",
    fileName: "tricou-logo.ng.png"
  },
];
